### ISSUE TITLE
Tkinter 'lab_key' KeyError

### ISSUE THREAD

**Issue by AnneSWarlaumont** [SeedlingsBabylab/idslabel#6]
Getting errors whenever I try to do a bunch of things (enter coder name, load blocks, etc.). See what I copied and pasted from the terminal window below. I wonder if this might be the same error causing Amanda's lab not to be able to load blocks. Thanks in advance!

Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 304, in codername_entered
  File "idslabel.py", line 701, in parse_config
  File "idsserver.py", line 38, in **init**
  File "idsserver.py", line 45, in parse_config
KeyError: 'lab_key'
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 530, in set_clip_path
  File "idslabel.py", line 819, in load_previously_downl_blocks
  File "idsserver.py", line 66, in lab_info_ping
  File "idsserver.py", line 42, in parse_config
TypeError: coercing to Unicode: need string or buffer, NoneType found
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 651, in get_blocks
  File "idsserver.py", line 101, in get_block
AttributeError: 'NoneType' object has no attribute 'codername'
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 530, in set_clip_path
  File "idslabel.py", line 819, in load_previously_downl_blocks
  File "idsserver.py", line 66, in lab_info_ping
  File "idsserver.py", line 42, in parse_config
TypeError: coercing to Unicode: need string or buffer, NoneType found
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 666, in add_user_to_server
  File "idsserver.py", line 84, in add_user_to_server
AttributeError: 'NoneType' object has no attribute 'codername'

Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 304, in codername_entered
  File "idslabel.py", line 701, in parse_config
  File "idsserver.py", line 38, in **init**
  File "idsserver.py", line 45, in parse_config
KeyError: 'lab_key'
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 670, in load_config_json
  File "idslabel.py", line 701, in parse_config
  File "idsserver.py", line 38, in **init**
  File "idsserver.py", line 45, in parse_config
KeyError: 'lab_key'
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 666, in add_user_to_server
  File "idsserver.py", line 84, in add_user_to_server
AttributeError: 'NoneType' object has no attribute 'codername'

**Comment by andreiamatuni** [comment]
Just realized i didn't update some part of the config.json. about to send a new one.

**Comment by AnneSWarlaumont** [comment]
Thanks for the fast response! New errors:

Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 304, in codername_entered
  File "idslabel.py", line 701, in parse_config
  File "idsserver.py", line 38, in **init**
  File "idsserver.py", line 48, in parse_config
KeyError: 'server_urls'
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 530, in set_clip_path
  File "idslabel.py", line 819, in load_previously_downl_blocks
  File "idsserver.py", line 66, in lab_info_ping
  File "idsserver.py", line 42, in parse_config
TypeError: coercing to Unicode: need string or buffer, NoneType found
Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 651, in get_blocks
  File "idsserver.py", line 101, in get_block
AttributeError: 'NoneType' object has no attribute 'codername'

**Comment by andreiamatuni** [comment]
whoops, missed the server_urls key. about to send another update, sorry about that

**Comment by AnneSWarlaumont** [comment]
Working now—thanks!!
