### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by AnneSWarlaumont** [SeedlingsBabylab/idslabel#7]
Worked this morning. Trying this afternoon to show RAs how it works and got this connection error. Thanks in advance!

Exception in Tkinter callback
Traceback (most recent call last):
  File "lib-tk/Tkinter.py", line 1537, in **call**
  File "idslabel.py", line 977, in get_training_blocks
  File "idsserver.py", line 140, in get_training_block
  File "requests/api.py", line 111, in post
  File "requests/api.py", line 57, in request
  File "requests/sessions.py", line 475, in request
  File "requests/sessions.py", line 585, in send
  File "requests/adapters.py", line 467, in send
ConnectionError: HTTPConnectionPool(host='169.236.169.136', port=8080): Max retries exceeded with url: /v1/get-block/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x114be8fd0>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by andreiamatuni** [comment]
Was the server rebooted or something? Connection failed for me too. ssh'ed in and saw idsserver wasn't running, and no signs of having crashed with an error. Just restarted it and it works again.

**Comment by AnneSWarlaumont** [comment]
I did have to reboot to fix another process that uses the server. Good to know that if we need to reboot, we need to let you know that idsserver needs restarting too. Thanks!

**Comment by andreiamatuni** [comment]
That's a relief. If you hadn't rebooted then it would mean something is probably deeply wrong with idsserver.
